name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Gatsuby
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build